### ISSUE TITLE
Feed bug fixes to upstream

### ISSUE THREAD

**Issue by itamarst** [jneem/imbl#58]
It looks like `im` is starting to get some maintenance again, so might be useful to feed the bug fixes you've made (to `Vector` IIRC?) back upstream. And more broadly seeing if you can collaborate.

**Comment by jneem** [comment]
Yes, definitely! If all goes well, I'll probably just archive this and everyone can just go back to `im`.

**Comment by mlgiraud** [comment]
Hi, what are your current plans on im and imbl? To me it doesn't look like im is getting any maintenance and we are interested in further contributing to either of these creates, since we heavily rely on copy on write functionality for our project.

Are there any plans on supporting the Rc version again (we don't need thread safety), and if so, what work would need to be done on that front? Maybe we can contribute something?

**Comment by jneem** [comment]
I never had any success in pushing fixes upstream so I gave up on that (and will close this issue).

My only ambition for this fork is for it to be "maintained" in the sense that I respond more-or-less promptly to issues and fixes. I'm happy to accept contributions that don't make things scarier to maintain.

Regarding the Rc version specifically, the old version involved both code generation and some tricky unsafe code (especially in the `pool` feature). I wouldn't want to reintroduce either of those, but I'd be happy to add a version that avoids them. For example, I think it may now be possible to use GATs for the implementation.
